import { test, expect } from '@playwright/test';

test('cover wall moves, pauses on hover and focus, resumes, and opens details',async({page},testInfo)=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');
 const column=page.getByTestId('book-column-0'),track=column.locator('.wall-track');
 await expect(track).toBeVisible();
 await page.mouse.move(0,0);
 const transform=()=>track.evaluate(el=>getComputedStyle(el).transform);
 const initial=await transform();
 await expect.poll(transform).not.toBe(initial);
 await column.hover({position:{x:20,y:120}});
 await expect(track).toHaveCSS('animation-play-state','paused');
 const stopped=await transform();await page.waitForTimeout(350);
 expect(await transform()).toBe(stopped);
 await page.mouse.move(0,0);
 await expect(track).toHaveCSS('animation-play-state','running');
 await expect.poll(transform).not.toBe(stopped);
 const cover=column.locator('.wall-book').first();
 await cover.focus();
 await expect(track).toHaveCSS('animation-play-state','paused');
 const label=await cover.getAttribute('aria-label');
 await cover.click();
 await expect(page.getByAltText('Cover of '+label.slice(5),{exact:true})).toBeVisible();
 await expect(track).toHaveCSS('animation-play-state','paused');
 await page.screenshot({path:testInfo.outputPath('book-details.png'),fullPage:true});
 await page.getByRole('button',{name:'Next book',exact:true}).click();
 await expect(page.getByAltText('Cover of '+label.slice(5),{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Pause scrolling',exact:true}).click();
 await expect(track).toHaveCSS('animation-play-state','paused');
 await page.getByRole('button',{name:'Resume scrolling',exact:true}).click();
 await page.mouse.move(0,0);
 await page.getByRole('heading',{name:'Find your next favourite book.',exact:true}).click();
 await expect(track).toHaveCSS('animation-play-state','running');
 await page.screenshot({path:testInfo.outputPath('bookclub-catalog.png'),fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(track).toHaveCSS('animation-name','none');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1)).toBe(true);
 await page.screenshot({path:testInfo.outputPath('bookclub-mobile.png'),fullPage:true});
 expect(errors).toEqual([]);
});

test('signup choice, real account, library saving, reading state and removal',async({page})=>{
 const errors=[],failedApi=[];page.on('pageerror',error=>errors.push(error.message));
 page.on('response',response=>{if(response.url().includes('/api/')&&response.status()>=400)failedApi.push(response.status()+' '+response.url());});
 await page.goto('/');
 await page.getByRole('button',{name:'♡ Save to my library',exact:true}).first().click();
 await page.getByRole('link',{name:'Create an account',exact:true}).click();
 const username='reader'+Date.now();
 await page.getByLabel('Email address').fill(username+'@example.test');
 await page.getByLabel('Username',{exact:true}).fill(username);
 await page.getByLabel('Password',{exact:true}).fill('TestOnlyPassword1!');
 await page.getByLabel('Re-Enter Password').fill('TestOnlyPassword1!');
 await page.getByRole('button',{name:'Create Account',exact:true}).click();
 await expect(page).toHaveURL(/setPreferences/);
 await page.goto('/');
 const card=page.locator('.catalog-card').first();await expect(card).toBeVisible();
 const title=await card.locator('h3').innerText();
 await card.getByRole('button',{name:'♡ Save to my library',exact:true}).click();
 await expect(card.getByRole('button',{name:'✓ In your library',exact:true})).toBeDisabled();
 await page.getByRole('link',{name:'View my library',exact:true}).click();
 await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:title,exact:true}).click();
 await page.getByRole('button',{name:'Mark As Read',exact:true}).click();
 await expect(page.getByRole('button',{name:'Mark As Unread',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByLabel('Reading status').selectOption('read');
 await page.getByRole('button',{name:title,exact:true}).click();
 await page.getByRole('button',{name:'Remove From Library',exact:true}).click();
 await expect(page.getByText(/Your library is empty/)).toBeVisible();
 expect(errors).toEqual([]);expect(failedApi).toEqual([]);
});
