const router = require('express').Router();
const c = require('../controllers/bookController');
const { isLoggedIn, asyncRoute: run } = require('./middleware/auth');
router.get('/get/:bookName', run(c.getBookByName));
router.get('/get/db/:bookName', run(c.getBookByNameInDatabase));
router.get('/get', isLoggedIn, run(c.getBookRecommendation));
router.get('/get/by/genre/:genre', run(c.getBookRecommendationByGenre));
router.post('/accept', isLoggedIn, run(c.acceptBookRecommendation));
router.post('/reject', isLoggedIn, run(c.rejectBookRecommendation));
router.post('/reject/undo', isLoggedIn, run(c.undoRejection));
router.post('/set/rating/:bookName', isLoggedIn, run(c.setBookRating));
module.exports = router;
