import { request } from './request';
export const getBookByName = title => request('/books/get/' + encodeURIComponent(title));
export const getBookByNameInDatabase = title => request('/books/get/db/' + encodeURIComponent(title));
const query = options => options ? '?' + new URLSearchParams({catalog:'1',...options}) : '';
export const getBookByGenre = (genre,options) => request('/books/get/by/genre/' + encodeURIComponent(genre)+query(options));
export const getRecommendations = options => request('/books/get'+query(options));
export const getBookDetails = book => request('/books/get/'+encodeURIComponent(book.title)+'?work='+encodeURIComponent(book.id.replace('/works/','')));
export const acceptBook = (body, sessionID) => request('/books/accept', { method: 'POST', body, sessionID });
export const rejectBook = (body, sessionID) => request('/books/reject', { method: 'POST', body, sessionID });
export const undoRejectBook = body => request('/books/reject/undo', { method: 'POST', body });
export const leaveBookRating = (body, title) => request('/books/set/rating/' + encodeURIComponent(title), { method: 'POST', body });
