import { request } from './request';
const name = encodeURIComponent;
export const getUserByUserName = username => request('/users/get/' + name(username));
export const getAllUsers = () => request('/users/get');
export const createAccount = body => request('/users/create', { method: 'POST', body });
export const login = body => request('/users/login', { method: 'POST', body });
export const logout = (body, sessionID) => request('/users/logout', { method: 'POST', body, sessionID });
export const changePassword = (body, sessionID) => request('/users/update', { method: 'PUT', body, sessionID });
export const deleteAccount = (body, sessionID) => request('/users/delete', { method: 'DELETE', body, sessionID });
const get = (path, username, sessionID) => request(`/users/get/${path}/${name(username)}`, { sessionID });
const set = (path, username, body) => request(`/users/set/${path}/${name(username)}`, { method: 'POST', body });
export const getPreferencesByUsername = (username, sessionID) => get('preferences', username, sessionID);
export const setPreferencesByUsername = (username, body) => set('preferences', username, body);
export const getMyLibraryByUsername = (username, sessionID) => get('myLibrary', username, sessionID);
export const setMyLibraryByUsername = (username, body) => set('myLibrary', username, body);
export const getMyReadBookByUsername = (username, sessionID) => get('myReadBook', username, sessionID);
export const markBookAsRead = (username, body) => set('myReadBook', username, body);
export const getMyUnReadBookByUsername = (username, sessionID) => get('myUnReadBook', username, sessionID);
export const markBookAsUnRead = (username, body) => set('myUnReadBook', username, body);
